#!/usr/bin/env bash
# gen-env.sh — generate a HikRAD .env with fresh secrets (FR-49.1, contract C5).
#
# Usage: gen-env.sh [--env dev|prod] [--force] [OUTPUT_PATH]
#   OUTPUT_PATH defaults to <repo>/deploy/.env
#   --env       HIKRAD_ENV value (default: dev; scripts/install.sh passes prod)
#   --force     overwrite an existing file (default: refuse)
#
# Never prints secrets to stdout; the file is created mode 0600.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT=""
HIKRAD_ENV_VALUE="dev"
FORCE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --env)
            HIKRAD_ENV_VALUE="${2:?--env requires dev|prod}"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        -h|--help)
            sed -n '2,10p' "$0"
            exit 0
            ;;
        *)
            OUT="$1"
            shift
            ;;
    esac
done

case "$HIKRAD_ENV_VALUE" in
    dev|prod) ;;
    *) echo "error: --env must be dev or prod, got '$HIKRAD_ENV_VALUE'" >&2; exit 1 ;;
esac

[ -n "$OUT" ] || OUT="$SCRIPT_DIR/../deploy/.env"

if [ -e "$OUT" ] && [ "$FORCE" -ne 1 ]; then
    echo "error: $OUT already exists — refusing to overwrite secrets (use --force)" >&2
    exit 1
fi

command -v openssl >/dev/null 2>&1 || { echo "error: openssl is required" >&2; exit 1; }

# URL-safe (hex) DB password so HIKRAD_DB_URL needs no escaping.
PG_PASSWORD="$(openssl rand -hex 24)"
# 32 bytes base64 — AES-256-GCM key for subscriber password encryption (NFR-4.2).
ENCRYPTION_KEY="$(openssl rand -base64 32)"
JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
# Backup archive passphrase (FR-51.1, sub-PRD 06 open question — decided:
# archives are passphrase-encrypted). install.sh prints this once to the
# install summary so the operator has an out-of-band copy; losing both that
# and this file's copy makes existing backups permanently unrecoverable by
# design (no vendor escrow) — see docs/ops/backup-restore.md.
BACKUP_PASSPHRASE="$(openssl rand -base64 24 | tr -d '\n')"
# Shared secret authenticating hikrad-api's socket calls to hikrad-updaterd
# (FR-86.2, v2 phase 7) — same generation recipe as HIKRAD_JWT_SECRET. Read by
# both sides from this one file: the daemon via its systemd EnvironmentFile,
# hikrad-api via its compose environment: block. No separate provisioning step.
HIKRAD_UPDATER_TOKEN="$(openssl rand -base64 32 | tr -d '\n')"

umask 077
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# HikRAD environment — generated by scripts/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Contains secrets: keep mode 0600, never commit, include in backups (FR-51.1).
# Env name contract: C5 in docs/phases/phase-1-foundation/00-phase.md.

POSTGRES_USER=hikrad
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=hikrad

HIKRAD_DB_URL=postgres://hikrad:${PG_PASSWORD}@postgres:5432/hikrad?sslmode=disable
HIKRAD_REDIS_URL=redis://redis:6379/0
HIKRAD_ENCRYPTION_KEY=${ENCRYPTION_KEY}
HIKRAD_JWT_SECRET=${JWT_SECRET}
HIKRAD_ENV=${HIKRAD_ENV_VALUE}

# Backup (FR-51): schedule/retention are Settings > Backups-configurable in
# the panel too; these are the values the hikrad CLI's backup command and the
# nightly cron entry fall back to when unset there.
HIKRAD_BACKUP_PASSPHRASE=${BACKUP_PASSPHRASE}
HIKRAD_BACKUP_RETENTION=14

# One-click updater (FR-86, v2 phase 7): shared token between hikrad-updaterd
# (host daemon) and hikrad-api (relay). Never sent anywhere except the local
# unix socket between them.
HIKRAD_UPDATER_TOKEN=${HIKRAD_UPDATER_TOKEN}
EOF

echo "wrote $OUT (HIKRAD_ENV=${HIKRAD_ENV_VALUE})"
