package radius

// FreeRADIUS client-list generation (FR-13.2). Decision (documented in
// deploy/freeradius/README.md): rather than point FreeRADIUS's rlm_sql at the
// nas table — which would force plaintext secrets into the database and break
// NFR-4 — hikrad-api owns the source of truth (the encrypted nas table) and
// regenerates a plain clients file that FreeRADIUS $INCLUDEs, decrypting each
// secret only in this process. The authorize-time known-NAS check (nasRegistry)
// is what makes a newly-created NAS take effect instantly with no restart
// (AC-13a); this file is the transport-layer hardening that FreeRADIUS applies
// on its next reload.

import (
	"bufio"
	"context"
	"fmt"
	"net"
	"os"
	"strings"
	"time"

	"github.com/hikrad/hikrad/internal/platform/crypto"
	"github.com/jackc/pgx/v5/pgxpool"
)

// controlSocketPathEnv names the FreeRADIUS control socket (sites-enabled/
// control-socket) reloadFreeRADIUS connects to; empty disables the reload
// call entirely (unit tests, environments wiring reload another way).
const controlSocketPathEnv = "HIKRAD_RADIUS_CONTROL_SOCKET"

// clientsPathEnv names the file FreeRADIUS $INCLUDEs; empty disables the
// file-generation side effect (unit tests, environments wiring clients another
// way). The regenerated content is always returned so callers/tests can assert
// on it regardless of whether a path is configured.
const clientsPathEnv = "HIKRAD_RADIUS_CLIENTS_PATH"

// generateClientsConf renders a FreeRADIUS clients.conf fragment for every
// enabled NAS. shortname is the NAS id (stable, unique); require_message_
// authenticator stays no for MikroTik compatibility (matches the dev client).
func generateClientsConf(ctx context.Context, db *pgxpool.Pool) (string, error) {
	nas, err := listNAS(ctx, db)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# HikRAD generated clients — DO NOT EDIT. Source: nas table (FR-13.2).\n")
	b.WriteString("# Regenerated by hikrad-api on every NAS mutation.\n\n")
	for _, n := range nas {
		if !n.Enabled {
			continue
		}
		secret, derr := crypto.Decrypt(n.SecretEnc)
		if derr != nil {
			return "", fmt.Errorf("radius: decrypt secret for nas %s: %w", n.ID, derr)
		}
		fmt.Fprintf(&b, "client nas_%s {\n", strings.ReplaceAll(n.ID, "-", "_"))
		fmt.Fprintf(&b, "\tipaddr = %s\n", n.IP)
		fmt.Fprintf(&b, "\tsecret = %s\n", quoteSecret(string(secret)))
		fmt.Fprintf(&b, "\tshortname = %s\n", n.Name)
		b.WriteString("\trequire_message_authenticator = no\n")
		b.WriteString("}\n\n")
	}
	return b.String(), nil
}

// quoteSecret double-quotes and escapes a secret for FreeRADIUS's config
// parser (backslash and double-quote are the meaningful metacharacters).
func quoteSecret(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// regenerateClients rebuilds the clients file (if a path is configured) and
// triggers a reload. Best-effort: a write failure is logged, never surfaced to
// the API caller, because the authorize-time known-NAS check already enforces
// the registry — this only refreshes FreeRADIUS's transport-layer client list.
func (m *module) regenerateClients(ctx context.Context) {
	conf, err := generateClientsConf(ctx, m.db)
	if err != nil {
		m.log.Error("radius: generate clients conf failed", "error", err)
		return
	}
	path := os.Getenv(clientsPathEnv)
	if path == "" {
		return
	}
	if err := os.WriteFile(path, []byte(conf), 0o640); err != nil {
		m.log.Error("radius: write clients conf failed", "path", path, "error", err)
		return
	}
	m.reloadFreeRADIUS()
}

// reloadFreeRADIUS asks FreeRADIUS to re-read its config over the control
// socket (deploy/freeradius/sites-enabled/control-socket, FR-13.2/AC-13a) —
// the same "reload" command `radmin` sends, piped directly since the wire
// protocol is a plain text command/response exchange once connected (peercred
// auth passes implicitly; no separate handshake). A missing/unreachable
// socket (path unset, FreeRADIUS mid-restart, socket not created yet) is
// logged and swallowed, never surfaced to the API caller — the regenerated
// file on disk is already correct and the authorize-time known-NAS check
// (AC-13a) already made the NAS usable; this only refreshes FreeRADIUS's own
// transport-layer client list, best-effort, same as the file write above.
func (m *module) reloadFreeRADIUS() {
	path := os.Getenv(controlSocketPathEnv)
	if path == "" {
		return
	}
	conn, err := net.DialTimeout("unix", path, 2*time.Second)
	if err != nil {
		m.log.Warn("radius: control socket dial failed (clients file is still correct on disk)", "path", path, "error", err)
		return
	}
	defer conn.Close()

	_ = conn.SetDeadline(time.Now().Add(3 * time.Second))
	r := bufio.NewReader(conn)
	// FreeRADIUS's control socket sends nothing until spoken to — it's the
	// client's turn first, unlike a banner-first protocol (found live: an
	// initial read here just ate the whole deadline waiting for bytes that
	// never came, so the write always timed out).
	if _, err := conn.Write([]byte("reload\n")); err != nil {
		m.log.Warn("radius: control socket reload command failed", "path", path, "error", err)
		return
	}
	resp, _ := r.ReadString('\n')
	m.log.Info("radius: clients file regenerated; FreeRADIUS reload sent", "response", strings.TrimSpace(resp))
}
