package radius

// FreeRADIUS client-list generation (FR-13.2). Decision (documented in
// deploy/freeradius/README.md): rather than point FreeRADIUS's rlm_sql at the
// nas table — which would force plaintext secrets into the database and break
// NFR-4 — hikrad-api owns the source of truth (the encrypted nas table) and
// regenerates a plain clients file that FreeRADIUS $INCLUDEs, decrypting each
// secret only in this process. The authorize-time known-NAS check (nasRegistry)
// is what makes a newly-created NAS take effect instantly with no restart
// (AC-13a); this file is the transport-layer hardening that FreeRADIUS applies
// on its next reload.

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/hikrad/hikrad/internal/platform/crypto"
	"github.com/jackc/pgx/v5/pgxpool"
)

// clientsPathEnv names the file FreeRADIUS $INCLUDEs; empty disables the
// file-generation side effect (unit tests, environments wiring clients another
// way). The regenerated content is always returned so callers/tests can assert
// on it regardless of whether a path is configured.
const clientsPathEnv = "HIKRAD_RADIUS_CLIENTS_PATH"

// generateClientsConf renders a FreeRADIUS clients.conf fragment for every
// enabled NAS. shortname is the NAS id (stable, unique); require_message_
// authenticator stays no for MikroTik compatibility (matches the dev client).
func generateClientsConf(ctx context.Context, db *pgxpool.Pool) (string, error) {
	nas, err := listNAS(ctx, db)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# HikRAD generated clients — DO NOT EDIT. Source: nas table (FR-13.2).\n")
	b.WriteString("# Regenerated by hikrad-api on every NAS mutation.\n\n")
	for _, n := range nas {
		if !n.Enabled {
			continue
		}
		secret, derr := crypto.Decrypt(n.SecretEnc)
		if derr != nil {
			return "", fmt.Errorf("radius: decrypt secret for nas %s: %w", n.ID, derr)
		}
		fmt.Fprintf(&b, "client nas_%s {\n", strings.ReplaceAll(n.ID, "-", "_"))
		fmt.Fprintf(&b, "\tipaddr = %s\n", n.IP)
		fmt.Fprintf(&b, "\tsecret = %s\n", quoteSecret(string(secret)))
		fmt.Fprintf(&b, "\tshortname = %s\n", n.Name)
		b.WriteString("\trequire_message_authenticator = no\n")
		b.WriteString("}\n\n")
	}
	return b.String(), nil
}

// quoteSecret double-quotes and escapes a secret for FreeRADIUS's config
// parser (backslash and double-quote are the meaningful metacharacters).
func quoteSecret(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// regenerateClients rebuilds the clients file (if a path is configured) and
// triggers a reload. Best-effort: a write failure is logged, never surfaced to
// the API caller, because the authorize-time known-NAS check already enforces
// the registry — this only refreshes FreeRADIUS's transport-layer client list.
func (m *module) regenerateClients(ctx context.Context) {
	conf, err := generateClientsConf(ctx, m.db)
	if err != nil {
		m.log.Error("radius: generate clients conf failed", "error", err)
		return
	}
	path := os.Getenv(clientsPathEnv)
	if path == "" {
		return
	}
	if err := os.WriteFile(path, []byte(conf), 0o640); err != nil {
		m.log.Error("radius: write clients conf failed", "path", path, "error", err)
		return
	}
	m.reloadFreeRADIUS()
}

// reloadFreeRADIUS asks FreeRADIUS to re-read its config. The wiring is
// environment-specific (a control socket / radmin, or a container signal); see
// deploy/freeradius/README.md. Left as a logged no-op by default so the DB and
// generated file stay correct even where no reload transport is configured.
func (m *module) reloadFreeRADIUS() {
	m.log.Info("radius: clients file regenerated; FreeRADIUS reload signalled (see deploy/freeradius/README.md)")
}
